name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate Token
        run: echo "Token is ${TOKEN:0:7}..."
        env:
          TOKEN: ${{ secrets.METRICS_TOKEN }}

      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: lucfercas
          template: classic
          base: header, activity, community, repositories, metadata, languages
          config_timezone: Europe/London

      - name: Optimize SVG
        uses: lowlighter/metrics@latest
        with:
          optimize: svg
          experimental_features: --optimize-svg

      - name: Language Analysis
        uses: lowlighter/metrics@latest
        with:
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

      - name: Stars
        uses: lowlighter/metrics@latest
        with:
          plugin_stars: yes
          plugin_stars_limit: 4
          repositories_skipped: lucfercas/metrics, lucfercas/codewars

      - name: Topics
        uses: lowlighter/metrics@latest
        with:
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars
