name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lucfercas/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: lucfercas
          template: classic
          base: header, activity, community, repositories, metadata, languages,
          config_timezone: Europe/London
      - uses: lucfercas/metrics@latest
        with:
          optimize: svg
          experimental_features: --optimize-svg
      - uses: lucfercas/metrics@latest
        with:
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%    
      - uses: lucfercas/metrics@latest
        with:
          plugin_stars: yes
          plugin_stars_limit: 4
          repositories_skipped: lucfercas/metrics, lucfercas/codewars
      - uses: lucfercas/metrics@latest
        with:
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          
# Options
          
          
          
          
