name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      #- name: Validate Token
        #run: echo "Token is ${TOKEN:0:7}..."
        #env:
         # TOKEN: ${{ secrets.METRICS_TOKEN }}

      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: lucfercas
          template: classic
          #base: header, activity, community, repositories, metadata
          config_timezone: Europe/London
          config_display: columns
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes size, percentage
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming, data
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
